name: CI

on:
  push:
    branches:
      - master
      - beta
      - release
      - next
      - 'v*'
      - 'release-*'
      - 'lts-*'
  pull_request:
  merge_group:
  schedule:
    - cron:  '0 3 * * *' # daily, at 3am

concurrency:
   group: ci-${{ github.head_ref || github.ref }}
   cancel-in-progress: true

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: wyvox/action-setup-pnpm@v2
        with:
          node-version: 16
      - run: pnpm lint

  basic-tests:
    name: "Basic Tests - ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}-latest"

    strategy:
      matrix:
        os: [ubuntu, macOS, windows]

    steps:
      - uses: actions/checkout@v3
      - uses: wyvox/action-setup-pnpm@v2
        with:
          node-version: 16
      - run: pnpm test

  tests:
    name: "Node ${{ matrix.node-version }} - ${{ matrix.os }} "
    runs-on: "${{ matrix.os }}-latest"

    needs: [linting, basic-tests]

    strategy:
      fail-fast: false
      matrix:
        node-version: [16, 18, 20]
        os: [ubuntu, windows]

    steps:
      - uses: actions/checkout@v3
      - uses: wyvox/action-setup-pnpm@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: pnpm test:all

  feature-flags:
    name: "Feature: ${{ matrix.feature-flag }}"
    runs-on: ubuntu-latest

    needs: [linting, basic-tests]

    strategy:
      fail-fast: false
      matrix:
        feature-flag:
          - ENABLE_ALL_EXPERIMENTS
          - EMBROIDER
          - CLASSIC

    steps:
      - uses: actions/checkout@v3
      - uses: wyvox/action-setup-pnpm@v2
        with:
          node-version: 16
      - run: pnpm test:all
        env:
          "EMBER_CLI_${{ matrix.feature-flag }}": true
