name: CI

on:
  push:
    branches:
      - master
      - beta
      - release
      - next
      - 'v*'
      - 'release-*'
      - 'lts-*'
  pull_request:
  workflow_dispatch:
  merge_group:
  schedule:
    - cron: '0 3 * * *' # daily, at 3am

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - run: yarn install --frozen-lockfile --non-interactive
      - run: yarn lint

  basic-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - run: yarn install --frozen-lockfile --non-interactive
      - run: yarn test

  all-tests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 18
          - 20
        os:
          - ubuntu-latest
        include:
          - node-version: 18
            os: macos-latest
          - node-version: 18
            os: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - run: yarn install --frozen-lockfile --non-interactive
      - run: yarn test:all

  feature-flags:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        feature-flag:
          - ENABLE_ALL_EXPERIMENTS
          - EMBROIDER
          - CLASSIC

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - run: yarn install --frozen-lockfile --non-interactive
      - run: yarn test:all
        env:
          'EMBER_CLI_${{ matrix.feature-flag }}': true
